In [2]:
import numpy as np

In [3]:
array = [
    [3, 1, 2, 4],
    [2, 3, 4, 1],
    [1, 4, 3, 2],
    [3, 2, 1, 4]
]

np_array = np.array(array)
norm_array = np.sum(np_array**2, axis=1).reshape(-1,1)
print(norm_array)

[[30]
 [30]
 [30]
 [30]]


In [8]:
side = np_array.shape[0]
new_array = np.zeros((side, side), dtype=np.float64)
for i in range(0, side, 2):
    end_i = min(i+2, side)
    for j in range(0, side, 2):
        end_j = min(j+2, side)

        batch_i = np_array[i:end_i]
        batch_j = np_array[j:end_j].T

        dot_product = np.dot(batch_i, batch_j)
        norm_array_1 = norm_array[i:end_i]
        norm_array_2 = norm_array[i:end_j].T
        dists = np.sqrt(norm_array_1 + norm_array_2 - 2 * dot_product)
        new_array[i:end_i, j:end_j] = dists


ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [16]:
data = np.array([[1, 2], [3, 4]])
squared_sum = np.sum(data**2, axis=1)
print(squared_sum)
print(squared_sum.shape)

[ 5 25]
(2,)


In [21]:
arr = np.array([10, 20, 5, 7, 30, 1, 15, 25])
smallest_values = np.partition(arr, 5)[:6]
print(smallest_values)

for ind, element in enumerate(arr):
    print("Index:", ind, "Value:", element)

s = np.argpartition(arr, 5)[:6]
print(s)
for i in s:
    print("element:", arr[i], "index:", i)

[ 1  7  5 10 15 20]
Index: 0 Value: 10
Index: 1 Value: 20
Index: 2 Value: 5
Index: 3 Value: 7
Index: 4 Value: 30
Index: 5 Value: 1
Index: 6 Value: 15
Index: 7 Value: 25
[5 3 2 0 6 1]
element: 1 index: 5
element: 7 index: 3
element: 5 index: 2
element: 10 index: 0
element: 15 index: 6
element: 20 index: 1


In [36]:
from scipy.stats import mode

arr = np.array([3,5,2,5,3,6,2,7,2,2,67,7,7,42,2,3,5,6,4,2,2,2,21,5,6,77,7,7,7,7,7,7,7,7,7,7,77,3,2,4])
# mode_result = mode(arr)
# print(mode_result)

# mode_value = mode_result.mode[1]

x, counts = np.unique(arr, return_counts=True)
ind = np.argmax(counts)
y = x[np.argmax(counts)]
print(y)

7
