In [2]:
import os
import numpy as np
from scipy.stats import binom
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
file_path = os.environ.get("TWO_GAUSSIAN_DATASET_HW2A_QUESTION3")
file = file_path + "coin_flips_outcome_hw2A_q4.txt"

dataset = np.loadtxt(file)
print("Top rows of the dataset: \n", dataset[:5])
print("Shape of the dataset: ", dataset.shape)

Top rows of the dataset: 
 [[0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1.]
 [1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Shape of the dataset:  (50, 20)


In [9]:
np.random.seed(89)
k = 3
prob_heads = np.random.randint(low=2, high=8, size=3)
prob_heads = prob_heads / 10
print("Initial probabilities of heads: ", prob_heads)

chance_of_pickining_coin = np.random.dirichlet([2, 5, 4]) 
print("Initial chance of picking coin k: ", chance_of_pickining_coin)

D = dataset.shape[1]
max_iter = 100
threshold = 1e-8
prev_likelihood = -np.inf
number_of_heads = np.sum(dataset, axis=1)


for iteration in range(max_iter):
    responsibilities = np.zeros((dataset.shape[0], k))

    for i in range(k):
        responsibilities[:, i] = chance_of_pickining_coin[i] * binom.pmf(number_of_heads, D, prob_heads[i])
    responsibilities /= responsibilities.sum(keepdims=True, axis=1)

    Nk = responsibilities.sum(axis=0)
    prob_heads = responsibilities.T @ number_of_heads / (Nk * D)
    chance_of_pickining_coin = Nk / dataset.shape[0]

    log_likelihood = np.sum(np.log(np.sum(chance_of_pickining_coin * binom.pmf(number_of_heads[:, np.newaxis], D, prob_heads), axis=1)))

    if log_likelihood - prev_likelihood < threshold:
        print("Converged after ", iteration, " iterations")
        break
    prev_likelihood = log_likelihood

print("Final probabilities of heads: ", prob_heads)
print("Final chance of picking coin k: ", chance_of_pickining_coin)

Initial probabilities of heads:  [0.5 0.6 0.7]
Initial chance of picking coin k:  [0.13280177 0.46742929 0.39976894]
Converged after  21  iterations
Final probabilities of heads:  [0.23691687 0.61003635 0.93172847]
Final chance of picking coin k:  [0.30681062 0.51463149 0.17855789]
